set_optimize("fastest")
set_languages("cxx20")
set_warnings("all", "extra")
set_encodings("utf-8")
add_rules("plugin.compile_commands.autoupdate")
includes("../xmake/opencl.lua")
add_intel_opencl()
add_includedirs("../base")

target("sync_test")
    set_kind("binary")
    add_files("src/sync_test.cxx", "../base/base.cxx")
