set_optimize("fastest")
set_languages("cxx20")
set_warnings("all", "extra")
set_encodings("utf-8")
add_rules("plugin.compile_commands.autoupdate")
includes("../xmake/opencl.lua")

target("convolution-cpu")
    set_kind("binary")
    add_intel_libs()
    add_files("src/convolution-cpu.cxx", "src/utils.cxx")

target("convolution-cpu-optimized")
    set_kind("binary")
    add_intel_libs()
    add_vectorexts("avx2")
    -- add_vectorexts("avx512")
    add_files("src/convolution-cpu-optimized.cxx", "src/utils.cxx")

target("convolution-opencl")
    set_kind("binary")
    add_intel_opencl()
    add_includedirs("../base")
    add_files("src/convolution-opencl.cxx", "../base/base.cxx", "src/utils.cxx")

target("convolution-opencl-optimized")
    set_kind("binary")
    add_intel_opencl()
    add_includedirs("../base")
    add_files("src/convolution-opencl-optimized.cxx", "../base/base.cxx", "src/utils.cxx")
