set_optimize("fastest")
set_languages("cxx20")
set_warnings("all", "extra")
set_encodings("utf-8")
add_rules("plugin.compile_commands.autoupdate")
includes("../xmake/opencl.lua")

target("convolution_cpu")
    set_kind("binary")
    add_intel_libs()
    add_files("src/convolution_cpu.cxx", "src/utils.cxx")

target("convolution_cpu_optimized")
    set_kind("binary")
    add_intel_libs()
    add_vectorexts("avx", "avx2")
    add_files("src/convolution_cpu_optimized.cxx", "src/utils.cxx")

target("convolution_opencl")
    set_kind("binary")
    add_intel_opencl()
    add_includedirs("../base")
    add_files("src/convolution_opencl.cxx", "../base/base.cxx", "src/utils.cxx")

target("convolution_opencl_optimized")
    set_kind("binary")
    add_intel_opencl()
    add_includedirs("../base")
    add_files("src/convolution_opencl_optimized.cxx", "../base/base.cxx", "src/utils.cxx")
