set_optimize("fastest")
set_languages("cxx20")
set_warnings("all", "extra")
set_encodings("utf-8")
add_rules("plugin.compile_commands.autoupdate")

local function add_intel_opencl()
    add_includedirs("C:\\Program Files (x86)\\Intel\\oneAPI\\compiler\\latest\\include")
    add_linkdirs("C:\\Program Files (x86)\\Intel\\oneAPI\\compiler\\latest\\lib")
    add_links("OpenCL")
end

target("rotate_image_opencl")
    set_kind("shared")
    add_defines("ROTATE_IMAGE_OPENCL_EXPORTS")
    add_files("src/rotate_image_opencl.cxx")
    add_intel_opencl()
    after_build(function (target)
        local targetfile = target:targetfile()
        os.cp(targetfile, os.projectdir())
    end)
    -- target:build
    -- after_build(function (target)
    --     os.cp("src/rotate_image_opencl.cl", target:targetdir())
    -- end)
